-- SIBAIM Housing Data - Complete Set (126 Records)
-- Refined Data with NULL Luas Lahan (m2) and Full Addresses
-- Format: Capitalize Each Word

TRUNCATE TABLE psu_housings;

INSERT INTO psu_housings (nama_perumahan, alamat, nama_pengembang, luas_lahan_m2, jumlah_rumah, status_serah_terima, no_ba_serah_terima, created_at, updated_at) VALUES
-- Records 1 - 24 (Recovered)
('Griya Bojongasri', 'Bojongbata, Pemalang', 'Pt. Dzikir Jaya Properti', NULL, NULL, 'Sudah Serah Terima', '600.2/03229/Disperkim', NOW(), NOW()),
('Bale Agung Bojongbata', 'Bojongbata, Pemalang', 'Pt. Cipta Selaras Hutama', NULL, NULL, 'Sudah Serah Terima', '600.2/003233/Disperkim', NOW(), NOW()),
('Griya Sidomukti', 'Taman, Pemalang', 'Pt. Bela Tata Miguna', NULL, NULL, 'Sudah Serah Terima', '600.2/003231/Disperkim', NOW(), NOW()),
('Oase 3 Th 3', 'Wanarejan Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '648/1637/Disperkim', NOW(), NOW()),
('Bale Agung Kaligelang', 'Kaligelang, Taman', 'Pt. Sundoro Asia', NULL, NULL, 'Sudah Serah Terima', '030/3913/Disperkim', NOW(), NOW()),
('The Premiere', 'Kaligelang, Taman', 'Pt. Cipta Selaras Hutama', NULL, NULL, 'Sudah Serah Terima', '600.2/003230/Disperkim', NOW(), NOW()),
('Bale Agung Banjardawa', 'Banjardawa, Taman', 'Pt. Cipta Baru Bersama', NULL, NULL, 'Sudah Serah Terima', '600.2/003228/Disperkim', NOW(), NOW()),
('Drans Quality 2', 'Bojongbata, Pemalang', 'Perorangan An Nur Amanah Yuliani', NULL, NULL, 'Sudah Serah Terima', '600.2/003232/Disperkim', NOW(), NOW()),
('Graha Ria Asri 4', 'Bojongbata, Pemalang', 'Pt. Duta Ria Properti', NULL, NULL, 'Sudah Serah Terima', '600.2/004289/Disperkim', NOW(), NOW()),
('Pir Iii', 'Sewaka, Pemalang', 'Pt. Rizki Group Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2358/Disperkim', NOW(), NOW()),
('Pir Vi', 'Bojongbata, Pemalang', 'Pt. Rizki Group Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2390/Disperkim', NOW(), NOW()),
('Pir V', 'Kaligelang, Taman', 'Pt. Rizki Group Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2391/Disperkim', NOW(), NOW()),
('Grand Bale Agung', 'Bojongbata, Pemalang', 'Pt. Cipta Selaras Hutama', NULL, NULL, 'Sudah Serah Terima', '650/3354/Disperkim', NOW(), NOW()),
('Grand Lestari Agung I', 'Taman, Pemalang', 'Pt. Utri Lestari', NULL, NULL, 'Sudah Serah Terima', '031/4092/Disperkim', NOW(), NOW()),
('Grand Lestari Agung Ii', 'Taman, Pemalang', 'Pt. Utri Lestari', NULL, NULL, 'Sudah Serah Terima', '031/4089/Disperkim', NOW(), NOW()),
('Victoria Regency', 'Taman, Pemalang', 'Pt. Inti Jaya Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2173', NOW(), NOW()),
('The Green Mansion', 'Taman, Pemalang', 'Pt. Inti Jaya Propertyndo', NULL, NULL, 'Sudah Serah Terima', '031/4090/Disperkim', NOW(), NOW()),
('Taman Mulia', 'Taman, Pemalang', 'Pt. Dzikir Jaya Tawakal', NULL, NULL, 'Sudah Serah Terima', '030/3207/Disperkim', NOW(), NOW()),
('Taman Mandiri', 'Taman, Pemalang', 'Pt. Dzikir Jaya Tawakal', NULL, NULL, 'Sudah Serah Terima', '030/3909/Disperkim', NOW(), NOW()),
('Griya Pesona Kalibaros', 'Taman, Pemalang', 'Pt. Dzikir Jaya Tawakal', NULL, NULL, 'Sudah Serah Terima', '030/3908/Disperkim', NOW(), NOW()),
('Royal Garden', 'Taman, Pemalang', 'Pt. Mulia Graha Pratama', NULL, NULL, 'Sudah Serah Terima', '031/4091/Disperkim', NOW(), NOW()),
('Oase 3 Tahap 1', 'Wanarejan Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '031/1683/Disperkim', NOW(), NOW()),
('Oase 3 Tahap 2', 'Wanarejan Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '640/836/Disperkim', NOW(), NOW()),
('Oase 4', 'Petarukan, Pemalang', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '050/2766/Disperkim', NOW(), NOW()),

-- Records 25 - 33 (Detailed Original)
('Pir Ii', 'Bojongbata, Pemalang', 'Pt. Rizki Group Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2357/Disperkim', NOW(), NOW()),
('Griya Bangunharjo', 'Taman, Pemalang', 'Pt. Bela Tata Miguna', NULL, NULL, 'Sudah Serah Terima', '050/1128/Perkim', NOW(), NOW()),
('Pir I', 'Bojongbata, Pemalang', 'Pt. Rizki Group Propertyndo', NULL, NULL, 'Sudah Serah Terima', '050/2359/Disperkim', NOW(), NOW()),
('Taman Seroja Indah', 'Beji, Taman', 'Pt. Karya Indah Subur Jaya', NULL, NULL, 'Sudah Serah Terima', '551.52/1945/Disperkim', NOW(), NOW()),
('Oase 1', 'Wanarejan Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '050/2767/Disperkim', NOW(), NOW()),
('Oase 2', 'Wanarejan Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Sudah Serah Terima', '050/2765/Disperkim', NOW(), NOW()),
('Perumnas Bojongbata', 'Bojongbata, Pemalang', 'Perumnas', NULL, NULL, 'Sudah Serah Terima', 'DIRUT/4456/77/VIII/86', NOW(), NOW()),
('Perumahan Baleza Permai 2', 'Kaligelang, Taman', 'Pt. Selin Jaya Abadi', NULL, NULL, 'Sudah Serah Terima', '600.2/1162/Disperkim/25', NOW(), NOW()),
('Perumahan Puri Praja Kencana', 'Mulyoharjo, Pemalang', 'Warga', NULL, NULL, 'Sudah Serah Terima', '600.2/1163/Disperkim/25', NOW(), NOW()),

-- Records 34 - 106 (Standard Original)
('Sapphire Residence', 'Beji, Taman', 'Pt. Karya Jaya Satria', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Sapphire Boutique', 'Bojongbata, Pemalang', 'Pt. Mitra Saphire', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bale Agung Kaligelang 2', 'Kaligelang, Taman', 'Pt. Bale Cipta Nusantara', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Banjar Arum', 'Banjardawa, Taman', 'Pt. Bela Tata Miguna', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bale Asri Wanamulya', 'Wanamulya, Pemalang', 'Pt. Cipta Selaras Hutama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Mulia Residence', 'Kaligelang, Taman', 'Pt. Dzikir Jaya Tawakal', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Grand Mulia', 'Banjardawa, Taman', 'Pt. Dzikir Jaya Tawakal', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bumi Randudongkal Permai', 'Lodaya, Randudongkal', 'Pt. Hunian Anugrah Abadi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Comal Argo Residence', 'Sidorejo, Comal', 'Pt. Kharisma Agung Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Green Sabana Kaligelang', 'Kaligelang, Taman', 'Pt. Oemah Insan Mandiri', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 3 Tahap 4', 'Wanareja Utara, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 5 Tahap 1', 'Taman, Pemalang', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 6', 'Beji, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 7', 'Bulu, Petarukan', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 8', 'Tegalmlati, Petarukan', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bumi Semingkir Damai', 'Semingkir, Randudongkal', 'Pt. Rhemananda Putri Graha', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 99 Tahap I', 'Kaligelang, Taman', 'Pt. Rizki Group Propertindo', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 8', 'Bojongbata, Pemalang', 'Pt. Rizki Group Propertindo', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 99 Tahap Ii', 'Kaligelang, Taman', 'Pt. Rizki Group Propertindo', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 99 Tahap Iii', 'Kaligelang, Taman', 'Pt. Rizki Group Propertindo', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Ndalem Widuri', 'Widuri, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Wisma Taman Agung', 'Taman, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Tanah Baya Asri', 'Tanah Baya, Randudongkal', 'Pt. Anugrah Bangun Indonesia', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bumi Pedurungan Pratama', 'Pedurungan, Taman', 'Pt. Aufa Pratama Perkasa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Rindu Alam', 'Jatirejo, Ampelgading', 'Pt. Bangun Nusa Lertari', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Hijau Randudongkal', 'Randudongkal, Pemalang', 'Pt. Candraniti Indah Lestari Abadi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Pesona Inat', 'Pelutan, Pemalang', 'Pt. Cipta Griya Pratama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('The Sambeng Village', 'Sambeng, Bantarbolang', 'Pt. Graha Alam Indo Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Amanah 2', 'Kaligelang, Taman', 'Pt. Griya Amanah Sejahtera', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Kalika Regency', 'Wanareja Utara, Taman', 'Pt. Griya Amanah Sejahtera', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Amanah Sejahtera', 'Kebondalem, Pemalang', 'Pt. Griya Amanah Sejahtera', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('The Ranch Regency', 'Kaligelang, Taman', 'Pt. Inti Jaya Properti', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Pelutan Indah', 'Pelutan, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Puri Praja Kencana', 'Mulyoharjo, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Asri Petarukan', 'Petarukan, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Han''S Residence', 'Lawangrejo, Pemalang', 'Pt. Karya Indah Subur Jaya', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Graha Mandiri Pemalang', 'Karangsari, Pemalang', 'Pt. Luhur Putra Mandiri', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Rancah Indah', 'Mendelem, Belik', 'Pt. Mandala Gogok Emas', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Grand Village Pedurungan', 'Pedurungan, Taman', 'Pt. Matahati Lintas Nusantara', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Royal Garden 2', 'Taman, Pemalang', 'Pt. Mulia Graha Pratama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 5 Tahap 2', 'Banjardawa, Taman', 'Pt. Omah Ageng Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Pandawa Asri', 'Sidorejo, Comal', 'Pt. Pandawa Jaya Sentosa', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Selaras Indah', 'Gembyang, Randudongkal', 'Pt. Recapital Propertindo Investama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Ndalem Agung', 'Petarukan, Pemalang', 'Pt. Recapital Propertindo Investama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perintis Regency', 'Petarukan, Pemalang', 'Pt. Recapital Propertindo Investama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Pelangi', 'Taman, Pemalang', 'Pt. Recapital Propertindo Investama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 7', 'Bojongbata, Pemalang', 'Pt. Rizki Group Propertindo', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Bhayangkara Residence 2', 'Beji, Taman', 'Pt. Royyan Aneka Karya', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Graha Samira Moga', 'Moga, Pemalang', 'Pt. Samira Graha Utama', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Baleza Permai', 'Wanamulya, Pemalang', 'Pt. Selin Jaya Abadi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Ndalem Agung 2 Sirangkang', 'Sirangkang, Petarukan', 'Pt. Taraca Propertindo Sejahtera', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Banjar Residence', 'Beji, Taman', 'Pt. Toni Jaya Makmur', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pandawa Asri 2', 'Sidorejo, Comal', 'Pt. Viva Bumi Permai', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Sugihwaras', 'Sugihwaras, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Hitta Regency', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Btn Cangklik', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Songgo Indah', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Harmony', 'Beji, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Permai Mulyoharjo', 'Mulyoharjo, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Anggur Refaonda', 'Bojongbata, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Kaligelang Permai', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('The Fontana Pemalang', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Javaland Pemalang', 'Taman, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Mutiara Residence', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Taman Asri', 'Taman, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Residence', 'Kaligelang, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Sukaiifa Residence', 'Pelutan, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Lavenia House', 'Pelutan, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Kecanden Indah', 'Beji, Taman', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Widuri', 'Widuri, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Grand Widuri Estate', 'Widuri, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Widuri Graha Pesona', 'Widuri, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Graha Sahara', 'Taman, Pemalang', 'Pt. Sudah Tidak Terdeteksi', NULL, NULL, 'Belum Serah Terima', NULL, NOW(), NOW()),

-- Records 107 - 126 (2025 Permits - Detailed)
('Permata Residence 2 Tahap 2', 'Jl. Raya Tegalmlati Dsn Kecapang Kelurahan Petarukan, Kecamatan Petarukan', 'Pt. Permata Sejahtera Group', NULL, 26, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Lestari', 'Jalan Kasuari I Danasari, Kecamatan Pemalang', 'Pt. Utri Lestari', NULL, 54, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Gemilang Permai', 'Jl. Lombok Desa Kaligelang, Kecamatan Taman', 'Pt. Karya Cipta Dana', NULL, 30, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 14', 'Jl. Flores Desa Kaligelang, Kecamatan Taman', 'Pt. Rizki Group Propertyndo', NULL, 100, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Oase 9', 'Jl. Seroja Desa Wanarejan Utara, Kec. Taman', 'Pt. Omah Ageng Sentosa', NULL, 98, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Oase 10', 'Jl. Seroja Kelurahan Beji, Kec. Taman', 'Pt. Omah Ageng Sentosa', NULL, 38, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Danasari Indah', 'Dukuh Gembyang Desa Danasari, Kecamatan Pemalang', 'Pt. Gemilang Surya Properti Kalirandu', NULL, 17, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Bale Asri Petarukan Tipe 36', 'Jl. Garuda Barat, Desa Petarukan, Kec. Petarukan', 'Pt. Cipta Selaras Hutama', NULL, 55, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Bale Asri Petarukan Tipe 45', 'Jl. Garuda Barat, Desa Petarukan, Kec. Petarukan', 'Pt. Cipta Selaras Hutama', NULL, 7, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Grand Bale Agung Pemalang 2', 'Kelurahan Bojongbata, Kecamatan Pemalang', 'Pt. Pemalang Kota Mandiri', NULL, 27, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Hitta Regency 2', 'Jl. Gatotkaca, Bandelan, Taman, Taman', 'Pt. Hitta Karya Utama', NULL, 30, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Andalan Sejahtera', 'Desa Wanamulya, Kecamatan Pemalang', 'Pt. Makro Arta Hutama', NULL, 46, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Madani Residence', 'Jl. Angkatan 45 Kel. Pelutan, Kec. Pemalang', 'Pt. Pilar Karya Properti', NULL, 63, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Griya Swargaloka', 'Jl. Dr. Cipto Mangunkusumo, Desa Kaligelang, Taman', 'Pt. Bela Tata Miguna', NULL, 111, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Griya Taman Arum', 'Jl. Gatotkaca, Desa Taman, Kec. Taman', 'Pt. Bela Tata Miguna', NULL, 159, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Pemalang Indah Regency 15', 'Jl. Flores, Desa Kaligelang, Kec. Taman', 'Pt. Rizki Group Propertyndo', NULL, 90, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Oase 10', 'Jl. Werkudoro, Desa Beji, Kec. Taman', 'Pt. Omah Ageng Sentosa', NULL, 91, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Grand Mulia Banjardawa Tahap 3', 'Desa Banjardawa, Kecamatan Taman', 'Pt. Dzikir Jaya Tawakal', NULL, 118, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Permata Residence 3', 'Jl. Raya Dusun Krandan, Desa Bulu, Kecamatan Petarukan', 'Pt. Permata Sejahtera Grup', NULL, 34, 'Belum Serah Terima', NULL, NOW(), NOW()),
('Perumahan Pandawa Asri 3', 'Jl. Cemara, Desa Sidorejo, Kecamatan Comal', 'Pt. Viva Bumi Permai', NULL, 42, 'Belum Serah Terima', NULL, NOW(), NOW());
